# Generated by Django 3.1.1 on 2020-09-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_blog_writer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
